### ISSUE TITLE
Testing outside of browser

### ISSUE THREAD

**Issue by richburdon** [amark/gun#692]
Is there a way to test gun outside of the browser (e.g., I'd like to build some simple unit tests for my app).

Currently I get:
~~~~
    TypeError: rad is not a function
      at ../../node_modules/gun/lib/store.js:20:4
~~~~

And assume that the store is attempting to use the browsers local storage?

Related to this: is it possible to write server side peers that use the same API. Ideally I'd like to create a stateless (ephemeral) lambda function that could get the current state and mutate it (i.e., not have a live socket connection). Is this in scope?

**Comment by bugs181** [comment]
For non-browser configurations, you'll likely just want to:
```
const Gun = require('gun/gun')
```

**Comment by amark** [comment]
@richburdon gonna assume you got this working with bug's recommend?

I'd be curious to see serverless stuff! IDK how well it will work (short-lived, GUN is usually longer-lived), but of any DB out there... it is kinda perfectly designed for this, if it can quickly pull from something like S3 fast enough. Tell us in the chat room ( https://gitter.im/amark/gun ) how it goes? I'd be super interested in an article on this!

**Comment by mmalmi** [comment]
I'm getting the same error after updating from 0.2019.413 to 0.2019.726:

```
 FAIL  __tests__/index_.js
  ● Test suite failed to run

    TypeError: Rad is not a function

      at start (node_modules/gun/axe.js:90:17)
      at Object.next (node_modules/gun/axe.js:37:4)
      at Object.next (node_modules/gun/sea.js:1072:15)
      at Object.next (node_modules/gun/lib/wire.js:85:10)
      at Object.next (node_modules/gun/nts.js:14:11)
      at Object.next (node_modules/gun/lib/server.js:9:11)
      at Object.next (node_modules/gun/gun.js:2204:12)
      at Function.onto [as on] (node_modules/gun/gun.js:198:41)
      at Gun.chain.opt (node_modules/gun/gun.js:849:9)
      at Function.Gun.create (node_modules/gun/gun.js:683:20)
      at new Gun (node_modules/gun/gun.js:655:15)
      at Object.<anonymous> (__tests__/index_.js:13:11)
```

**Comment by mmalmi** [comment]
Around gun/axe.js:90
```
console.log(Gun.window.Radix); // undefined
var Rad = (Gun.window||{}).Radix || USE('./lib/radix', 1);
console.log(Gun.window.Radix); // [radix function]
console.log(Rad); // {}
```
I'm in a node.js testing environment that provides the window object.

**Comment by amark** [comment]
Bleh! If it provides a `window` environment, I need it to behave like a Browser. Is there anyway you can tell the testing environment to just run the test in a real browser, or not provide a non-Browser-compatible `window`? They shouldn't be doing that.

**Comment by sirpy** [comment]
@mmalmi @amark @richburdon 
I use the following to run it on node.
I use the node-localstorage module.

import LocalStorage from 'node-localstorage'
global.window = {}
global.window.localStorage = new LocalStorage('./localStorage.tmp')
global.gun = Gun({ localStorge: false, peers: [Config.gunPublicUrl], axe: true, multicast: false })
global.Gun = Gun

**Comment by mboperator** [comment]
## Hey @richburdon , I just ran in to this issue running my tests on CircleCI.
<img width="814" alt="Screen Shot 2019-10-08 at 10 38 55 AM" src="https://user-images.githubusercontent.com/1007233/66418960-080f8580-e9b8-11e9-86fe-f1f6273c677f.png">

## I was able to get it working by simply mocking `gun` inside of my test.
<img width="595" alt="Screen Shot 2019-10-08 at 10 39 23 AM" src="https://user-images.githubusercontent.com/1007233/66418985-19f12880-e9b8-11e9-8cb2-7a23312198bf.png">

## Now all is well
<img width="335" alt="Screen Shot 2019-10-08 at 10 39 10 AM" src="https://user-images.githubusercontent.com/1007233/66419014-24abbd80-e9b8-11e9-8647-5ade288c34b9.png">

For more complex tests (IE: testing the integration between your state management & gun) I think jest's manual mocks would continue to suffice.

**Comment by mmalmi** [comment]
When running jest in jsdom mode, I fixed this error with `const radix = require('gun/lib/radix');`

**Comment by pszabop** [comment]
I've got a complete nodejs test environment using Tape, I'm even able to test multiple Gun peers interacting with each other.   I don't yet have a clean repo to share but I can share [this Gist](https://gist.github.com/pszabop/61c3b7c36aa5fe866834fda4531d9219).

The key is setting the right options in the constructor so that the standalone instance behaves well.  Also you have to force an exit as the last test, see related bugs about terminating a gun instance.

I've got other tests (not yet in a gist) where I can run multiple Gun instances in one process, which allows detailed and controlled interaction testing more quickly than firing up multiple docker instances.
